name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v3
      - uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_PAGES_BRANCH: pages
          CR_PR: 'true' # temporary
